language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  - DEPLOY=false DEPLOY_DOCS=false
# Setting the JDK which will do the deployment
matrix:
  exclude:
    - jdk: oraclejdk7
    - jdk: oraclejdk8
  include:
    - jdk: oraclejdk7
      env: DEPLOY=true DEPLOY_DOCS=false
    - jdk: oraclejdk8
      env: DEPLOY=false DEPLOY_DOCS=true
    
before_install:
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
  - ./.scripts/create-maven-settings.sh
script:
  - mvn clean verify
after_success:
  - ./.scripts/deploy-site.sh
  - ./.scripts/deploy.sh
