name: Doc deployment

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy_docs:

    runs-on: ubuntu-latest

    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H docs.bernardomg.com >> ~/.ssh/known_hosts
      shell: bash
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 8
        distribution: 'adopt'
    - name: Set up Maven settings
      uses: bernardo-mg/deployment-maven-settings-action@v1.1.2
      env:
        DEPLOY_DOCS_USER: ${{ secrets.DEPLOY_DOCS_USER }}
        DEPLOY_DOCS_PASSWORD: ${{ secrets.DEPLOY_DOCS_PASSWORD }}
        DEPLOY_DOCS_DEVELOP_USER: ${{ secrets.DEPLOY_DOCS_DEVELOP_USER }}
        DEPLOY_DOCS_DEVELOP_PASSWORD: ${{ secrets.DEPLOY_DOCS_DEVELOP_PASSWORD }}
        DEPLOY_DOCS_SITE: ${{ secrets.DEPLOY_DOCS_SITE }}
        DEPLOY_DOCS_DEVELOP_SITE: ${{ secrets.DEPLOY_DOCS_DEVELOP_SITE }}
    - name: Deploy development docs
      if: steps.extract_branch.outputs.branch == 'develop'
      run: mvn site site:deploy -B -P deployment,deployment-development --settings settings.xml
    - name: Deploy release docs
      if: steps.extract_branch.outputs.branch == 'master'
      run: mvn site site:deploy -B -P deployment,deployment-release --settings settings.xml
